# Generated by Django 4.2.7 on 2023-11-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments', '0002_alter_sentiment_status'),
        ('comments', '0002_comment_post_id_alter_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentiments.sentiment'),
        ),
    ]
